import { prisma } from '../src/lib/prisma';

// Comprehensive bin data across all major Indian cities
const binsData = [
  // Delhi NCR (Multiple locations)
  {
    name: "Connaught Place E-Waste Center",
    latitude: 28.6304,
    longitude: 77.2177,
    address: "Connaught Place, New Delhi, Delhi 110001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "tablet"]),
    currentFill: 25,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-DEL-001",
  },
  {
    name: "Nehru Place E-Waste Station",
    latitude: 28.5494,
    longitude: 77.2507,
    address: "Nehru Place, New Delhi, Delhi 110019",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor", "printer"]),
    currentFill: 45,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-DEL-002",
  },
  {
    name: "Dwarka Tech Hub",
    latitude: 28.5713,
    longitude: 77.0536,
    address: "Dwarka Sector 21, New Delhi, Delhi 110075",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "tablet", "charger"]),
    currentFill: 35,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 172800000),
    qrCode: "BIN-DEL-003",
  },
  {
    name: "Gurgaon Tech Hub",
    latitude: 28.4595,
    longitude: 77.0266,
    address: "Cyber City, Gurgaon, Haryana 122001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "headphones"]),
    currentFill: 45,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-GUR-001",
  },
  {
    name: "Gurgaon Sector 43 Recycling",
    latitude: 28.4744,
    longitude: 77.0457,
    address: "Sector 43, Gurgaon, Haryana 122001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor"]),
    currentFill: 60,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 28800000),
    qrCode: "BIN-GUR-002",
  },
  // Mumbai (Multiple locations)
  {
    name: "Bandra-Worli Sea Link Recycling",
    latitude: 19.0635,
    longitude: 72.8235,
    address: "Bandra West, Mumbai, Maharashtra 400050",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger"]),
    currentFill: 60,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 7200000),
    qrCode: "BIN-MUM-001",
  },
  {
    name: "Andheri Tech Recycle",
    latitude: 19.1196,
    longitude: 72.8465,
    address: "Andheri East, Mumbai, Maharashtra 400069",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor"]),
    currentFill: 35,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 172800000),
    qrCode: "BIN-MUM-002",
  },
  {
    name: "Powai Recycling Hub",
    latitude: 19.1198,
    longitude: 72.9050,
    address: "Hiranandani Gardens, Mumbai, Maharashtra 400076",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor", "printer"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-MUM-003",
  },
  // Bangalore (Multiple locations)
  {
    name: "Electronic City Recycling Hub",
    latitude: 12.8442,
    longitude: 77.6763,
    address: "Electronic City, Bangalore, Karnataka 560100",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "desktop", "printer"]),
    currentFill: 70,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 3600000),
    qrCode: "BIN-BLR-001",
  },
  {
    name: "Whitefield E-Waste Center",
    latitude: 12.9698,
    longitude: 77.7499,
    address: "Whitefield, Bangalore, Karnataka 560066",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "battery"]),
    currentFill: 40,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 28800000),
    qrCode: "BIN-BLR-002",
  },
  {
    name: "Koramangala Recycling Center",
    latitude: 12.9345,
    longitude: 77.6240,
    address: "Koramangala, Bangalore, Karnataka 560095",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "printer"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-BLR-003",
  },
  // Chennai (Multiple locations)
  {
    name: "T Nagar Electronics Recycling",
    latitude: 13.0403,
    longitude: 80.2336,
    address: "T Nagar, Chennai, Tamil Nadu 600017",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-CHE-001",
  },
  {
    name: "OMR Tech Hub",
    latitude: 12.8455,
    longitude: 80.2254,
    address: "Old Mahabalipuram Road, Chennai, Tamil Nadu 600097",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "tablet"]),
    currentFill: 45,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-CHE-002",
  },
  // Kolkata
  {
    name: "Salt Lake Tech Recycle",
    latitude: 22.5808,
    longitude: 88.4161,
    address: "Salt Lake City, Kolkata, West Bengal 700091",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "scanner"]),
    currentFill: 30,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-KOL-001",
  },
  {
    name: "New Town E-Waste Center",
    latitude: 22.5690,
    longitude: 88.4289,
    address: "New Town, Kolkata, West Bengal 700156",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 28800000),
    qrCode: "BIN-KOL-002",
  },
  // Hyderabad
  {
    name: "HITEC City E-Waste",
    latitude: 17.4483,
    longitude: 78.3915,
    address: "HITEC City, Hyderabad, Telangana 500081",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "headphones"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-HYD-001",
  },
  {
    name: "Gachibowli Tech Park Recycling",
    latitude: 17.4404,
    longitude: 78.3989,
    address: "Gachibowli, Hyderabad, Telangana 500032",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor"]),
    currentFill: 35,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 172800000),
    qrCode: "BIN-HYD-002",
  },
  // Pune
  {
    name: "Hinjewadi IT Park Recycling",
    latitude: 18.5992,
    longitude: 73.7392,
    address: "Hinjewadi, Pune, Maharashtra 411057",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "desktop", "monitor"]),
    currentFill: 65,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 7200000),
    qrCode: "BIN-PUN-001",
  },
  {
    name: "Magarpatta City E-Waste",
    latitude: 18.5361,
    longitude: 73.9275,
    address: "Magarpatta, Pune, Maharashtra 411013",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "tablet"]),
    currentFill: 40,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-PUN-002",
  },
  // Ahmedabad
  {
    name: "GIFT City E-Waste Center",
    latitude: 23.2179,
    longitude: 72.6369,
    address: "GIFT City, Gandhinagar, Gujarat 382355",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "cable"]),
    currentFill: 25,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-AHD-001",
  },
  {
    name: "Ahmedabad Tech Recycling",
    latitude: 23.0225,
    longitude: 72.5714,
    address: "Ahmedabad, Gujarat 380001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "monitor", "printer", "battery"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-AHD-002",
  },
  // Jaipur
  {
    name: "Malviya Nagar Tech Recycle",
    latitude: 26.8467,
    longitude: 75.8084,
    address: "Malviya Nagar, Jaipur, Rajasthan 302017",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "charger", "earphones"]),
    currentFill: 45,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 28800000),
    qrCode: "BIN-JAI-001",
  },
  {
    name: "Jaipur IT Hub",
    latitude: 26.9025,
    longitude: 75.8118,
    address: "RIICO IT Park, Jaipur, Rajasthan 302013",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "tablet"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-JAI-002",
  },
  // Bhopal
  {
    name: "Bhopal City Center",
    latitude: 23.2599,
    longitude: 77.4126,
    address: "MP Nagar, Bhopal, Madhya Pradesh 462011",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger"]),
    currentFill: 25,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-BPL-001",
  },
  {
    name: "Habibganj Recycling Point",
    latitude: 23.2306,
    longitude: 77.4127,
    address: "Habibganj, Bhopal, Madhya Pradesh 462016",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "headphones"]),
    currentFill: 60,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-BPL-002",
  },
  // Indore
  {
    name: "Indore Tech Park Recycling",
    latitude: 22.7196,
    longitude: 75.8577,
    address: "Super Corridor, Indore, Madhya Pradesh 452010",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor"]),
    currentFill: 35,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 172800000),
    qrCode: "BIN-IDR-001",
  },
  // Lucknow
  {
    name: "Gomti Nagar E-Waste Center",
    latitude: 26.8467,
    longitude: 80.9462,
    address: "Gomti Nagar, Lucknow, Uttar Pradesh 226010",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger"]),
    currentFill: 40,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-LKO-001",
  },
  // Chandigarh
  {
    name: "Sector 35 Tech Recycling",
    latitude: 30.7333,
    longitude: 76.7794,
    address: "Sector 35, Chandigarh 160001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "battery", "charger"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-CHD-001",
  },
  // Surat
  {
    name: "APDA Recycling Hub Surat",
    latitude: 21.1702,
    longitude: 72.8311,
    address: "Adajan, Surat, Gujarat 395009",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor", "battery"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-SRT-001",
  },
  // Kochi
  {
    name: "Kochi E-Waste Management",
    latitude: 9.9312,
    longitude: 76.2673,
    address: "Infopark, Kochi, Kerala 682030",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "monitor", "printer"]),
    currentFill: 45,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 28800000),
    qrCode: "BIN-KCH-001",
  },
  // Coimbatore
  {
    name: "Coimbatore E-Waste Facility",
    latitude: 11.0081,
    longitude: 76.9955,
    address: "Peelamedu, Coimbatore, Tamil Nadu 641004",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor", "keyboard"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-CBE-001",
  },
  // Nagpur
  {
    name: "Nagpur Tech Recycling",
    latitude: 21.1458,
    longitude: 79.0882,
    address: "Ramdaspeth, Nagpur, Maharashtra 440010",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "tablet"]),
    currentFill: 40,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-NGP-001",
  },
  // Ludhiana
  {
    name: "Ludhiana Smart Recycling",
    latitude: 30.9010,
    longitude: 75.8573,
    address: "Ludhiana, Punjab 141008",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "tablet", "battery"]),
    currentFill: 60,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-LDH-001",
  },
  // Visakhapatnam
  {
    name: "Visakhapatnam E-Waste Hub",
    latitude: 17.6869,
    longitude: 83.2185,
    address: "Vizag, Andhra Pradesh 530003",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "battery", "charger", "monitor"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-VZG-001",
  },
  // Mysore
  {
    name: "Mysore E-Waste Recycling",
    latitude: 12.2958,
    longitude: 76.6394,
    address: "Mysore, Karnataka 570001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor", "battery"]),
    currentFill: 40,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-MYS-001",
  },
  // Guwahati
  {
    name: "Guwahati E-Waste Center",
    latitude: 26.1445,
    longitude: 91.7362,
    address: "Guwahati, Assam 781001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "monitor", "keyboard", "charger"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 50400000),
    qrCode: "BIN-GWL-001",
  },
  // Patna
  {
    name: "Patna E-Waste Hub",
    latitude: 25.5941,
    longitude: 85.1376,
    address: "Patna, Bihar 800001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "tablet", "monitor", "battery"]),
    currentFill: 50,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 43200000),
    qrCode: "BIN-PTN-001",
  },
  // Raipur
  {
    name: "Raipur E-Waste Facility",
    latitude: 21.2514,
    longitude: 81.6296,
    address: "Raipur, Chhattisgarh 492001",
    acceptedTypes: JSON.stringify(["smartphone", "laptop", "printer", "monitor", "battery"]),
    currentFill: 55,
    maxCapacity: 100,
    status: "operational",
    lastEmptied: new Date(Date.now() - 86400000),
    qrCode: "BIN-RPR-001",
  },
];

async function seedBins() {
  console.log('🌱 Starting bin database seed...');
  
  for (const bin of binsData) {
    try {
      const existingBin = await prisma.bin.findFirst({
        where: { qrCode: bin.qrCode },
      });

      if (existingBin) {
        console.log(`✓ Bin ${bin.qrCode} already exists, skipping...`);
        continue;
      }

      const createdBin = await prisma.bin.create({
        data: {
          ...bin,
          qrCode: bin.qrCode,
        },
      });

      console.log(`✓ Created bin: ${createdBin.name} (${createdBin.qrCode})`);
    } catch (error) {
      console.error(`✗ Error creating bin ${bin.name}:`, error);
    }
  }

  console.log('✅ Bin database seed completed!');
}

// Main execution
seedBins()
  .catch((error) => {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
